[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# end of round effects
[[patches]] 
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
for _,v in ipairs(SMODS.get_card_areas('playing_cards', 'end_of_round')) do
'''
position = "before"
payload = '''
local num_carry_over = 2
G.GAME.SuikaLatro_carryover_balls = {}
if #SuikaLatro.balls <= num_carry_over then
    for i = 1, num_carry_over do
        for k, ball in ipairs(SuikaLatro.balls) do
            G.GAME.SuikaLatro_carryover_balls[k] = {}
            G.GAME.SuikaLatro_carryover_balls[k].x = ball.body:getX()
            G.GAME.SuikaLatro_carryover_balls[k].y = ball.body:getY()
            G.GAME.SuikaLatro_carryover_balls[k].id = ball.id
            G.GAME.SuikaLatro_carryover_balls[k].suit = ball.suit
            G.GAME.SuikaLatro_carryover_balls[k].enhancement = ball.enhancement
            G.GAME.SuikaLatro_carryover_balls[k].edition = ball.edition
            G.GAME.SuikaLatro_carryover_balls[k].seal = ball.seal
            G.GAME.SuikaLatro_carryover_balls[k].size = ball.size

            G.GAME.SuikaLatro_carryover_balls[k].perma_bonuses = {}
            for kk,vv in pairs(ball.perma_bonuses) do
                G.GAME.SuikaLatro_carryover_balls[k].perma_bonuses[kk] = v
            end
        end
    end
else
    local target_list = {}
    for k, ball in ipairs(SuikaLatro.balls) do
        target_list[k] = ball
    end
    for i = 1, num_carry_over do
        local ball, ball_id = pseudorandom_element(target_list, 'suika_carryover')
        target_list[ball_id] = nil
        G.GAME.SuikaLatro_carryover_balls[i] = {}
        G.GAME.SuikaLatro_carryover_balls[i].x = ball.body:getX()
        G.GAME.SuikaLatro_carryover_balls[i].y = ball.body:getY()
        G.GAME.SuikaLatro_carryover_balls[i].id = ball.id
        G.GAME.SuikaLatro_carryover_balls[i].suit = ball.suit
        G.GAME.SuikaLatro_carryover_balls[i].enhancement = ball.enhancement
        G.GAME.SuikaLatro_carryover_balls[i].edition = ball.edition
        G.GAME.SuikaLatro_carryover_balls[i].seal = ball.seal
        G.GAME.SuikaLatro_carryover_balls[i].size = ball.size

        G.GAME.SuikaLatro_carryover_balls[i].perma_bonuses = {}
        for kk,vv in pairs(ball.perma_bonuses) do
            G.GAME.SuikaLatro_carryover_balls[i].perma_bonuses[kk] = v
        end
    end

end

for k,v in ipairs(SuikaLatro.balls) do
    local x_pos, y_pos = v.body:getX(), v.body:getY()
    v.pos = {
        x = x_pos,
        y = y_pos,
    }
    
    SuikaLatro.retrig[v] = {'base'}
    if v.seal and v.seal == 'Red' then
        SuikaLatro.retrig[v][#SuikaLatro.retrig[v]+1] = 'Red'
    end
    SMODS.calculate_context({suika_ball_remain_repetition = true, other_ball = v})

    if v.debuff then SuikaLatro.retrig[v] = {'base'} end

    for i = 1, #SuikaLatro.retrig[v] do
        if SuikaLatro.retrig[v][i] == "Red" then
            G.E_MANAGER:add_event(Event({
                func = function()
                    SuikaLatro.f.seal_message(v.pos.x, v.pos.y, "Red")
                    return true
                end
            }))
        elseif type(SuikaLatro.retrig[v][i]) == 'table' then
            G.E_MANAGER:add_event(Event({
                func = function()
                    SuikaLatro.f.score_message_joker({
                        retriggers = 1,
                        obj = v,
                        juice_card = SuikaLatro.retrig[v][i],
                    })
                    return true
                end
            }))
        end
        if v.enhancement == 'm_gold' and not v.debuff then
            delay(1)
            G.E_MANAGER:add_event(Event({
                func = function()
                    SuikaLatro.f.enhancement_message(v.pos.x, v.pos.y, v.enhancement)
                return true
                end
            }))
        end
        if v.seal and v.seal == 'Blue' and not v.debuff then
            delay(1)
            G.E_MANAGER:add_event(Event({
                func = function()
                    SuikaLatro.f.seal_message(v.pos.x, v.pos.y, v.seal)
                return true
                end
            }))
        end
        G.E_MANAGER:add_event(Event({
            func = function()
                SMODS.calculate_context({suika_hand_individual_endofround = true, other_ball = v})
                return true
            end
        }))
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
G.STATE = G.STATES.ROUND_EVAL
'''
position = "after"
payload = '''
SuikaLatro.f.disable_suika()
SuikaLatro.retrig = {}
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
SMODS.calculate_context({setting_blind = true, blind = G.GAME.round_resets.blind})
'''
position = "after"
payload = '''
SuikaLatro.f.enable_suika()
SuikaLatro.f.reset_suika(true)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
self.HUD:recalculate()

G.E_MANAGER:add_event(Event({
    trigger = 'immediate',
    func = (function()
        unlock_notify()
        return true
    end)
  }))
'''
position = "after"
payload = '''
SuikaLatro.f.reset_suika()
if G.STATE == G.STATES.SELECTING_HAND then
    SuikaLatro.world_T.y = 2.5
end
if G.GAME.SuikaLatro_balls then
    for k,v in ipairs(G.GAME.SuikaLatro_balls) do
        table.insert(SuikaLatro.balls, Ball(v.x, v.y, v, 0, 0, nil, nil, nil, v.size))
    end
end
for k,v in pairs(G.GAME.hands) do 
    if not string.find(k, 'suika') then
        SMODS.PokerHand:take_ownership(k,
            {
            visible = function(self) return false end
            },
            true
        )
    end
end
'''
match_indent = true